### ISSUE TITLE
Compilation with Clang fails now

### ISSUE THREAD

**Issue by animeavi** [micros24/linux-xanmod-bore#58]
No sure if this is the right place to report it, but when I try to build the current version (6.9.8) with Clang, at the end of the compilation process, I get this error (don't have the full log anymore, sorry).

```
LD vmlinux
BTFIDS vmlinux
FAILED: load BTF from vmlinux: Invalid argument
```

I searched around for a bit and it looked it like in the past it was solved by adding `--skip_encoding_btf_enum64` to the pahole arguments, I tried editing the .mk file that ran pahole manually to add that and re-running just the build step with with `makepkg -e`, but I got the same result.

I ended giving up and just using GCC, but I thought I'd let you know.
The last version I successfully built with Clang was 6.9.1, but I wouldn't know where it broke.

**Comment by micros24** [comment]
I also had that problem on that release. What I discovered is that it's an upstream problem and it has been fixed since I was able to compile 6.9.9 with clang. Try to update your clang and llvm then see if that works.

**Comment by micros24** [comment]
Any updates for this issue?

**Comment by animeavi** [comment]
I'm no longer using this kernel so I can't test it, sorry.
